import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Lets Practice Next.js 13",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
		<html lang='en' className={`${geistSans.variable} ${geistMono.variable}`}>
			<body>
				<Navbar />
				{children}
			</body>
		</html>
	)
}
