import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "./page.module.css"
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
     <main className={styles.navbar}>
      <Link href={'/'}>
      <p>Home</p>
      </Link>
       <Link href={'/blogstatic'}>
      <p>Blog API Static</p>
      </Link>
      <Link href={'/people'}>
      <p>People List</p>
      </Link>
     
    </main>
        {children}
      </body>
    </html>
  );
}
